version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "4000:4000"
    links:
      - mongo
  mongo:
    container_name: mongo2
    image: mongo
    hostname: mongo2
    volumes:
      - ./mongo-volume:/data/db
    expose:
      - 27017
    ports:
      - 27011:27017